### ISSUE TITLE
Design and create an Adoptium MarketPlace data representation of a CDXA attestation

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/marketplace-api.adoptium.net#543]
Design and create an Adoptium MarketPlace data representation of a CDXA attestation, that supports Adoptium member vendors publishing a CDXA attestation as to the "Reproducible Verification" of an Adoptium MarketPlace release.

A Vendor should be able to:
- Handcraft and "sign" a CDXA attestation json document that confirms the Reproducible Verification of a target Adoptium marketplace release JDK binary
- A Vendor can also "attest" to the "Reproducible Verification" of their own release, eg.Temurin attest to "Reproducible Verification" of their own JDK binary.
- A standard method of "signing" the json document should be employed.
-

**Comment by andrew-m-leonard** [comment]
MarketPlace sketch:
![MarketPlaceReproVerified](https://github.com/user-attachments/assets/75922e14-4493-432b-80cf-4794d917d5a5)

**Comment by andrew-m-leonard** [comment]
MarketPlace sketch:
![MarketPlaceReproVerified](https://github.com/user-attachments/assets/40cb3f4f-db37-4b71-8dc5-347e8cfa521e)

**Comment by andrew-m-leonard** [comment]
@tellison @jiekang When you get a moment please, your thoughts on the above "sketch", thanks

**Comment by jiekang** [comment]
Sketch seems fine to me. I would probably make the logos smaller, square icons preferably.

**Comment by johnoliver** [comment]
In terms of API I think I would just add an Attestation link or object onto the `Release` rather than adding an extra endpoint

**Comment by andrew-m-leonard** [comment]
> In terms of API I think I would just add an Attestation link or object onto the `Release` rather than adding an extra endpoint

Thanks John,
There's a subtle difference from a Release, in that a Vendor could attest to the reproducibility of another Vendor separate from their own releases... however, having had a discussion we're going to move this out of the Marketplace-data completely as it doesn't seem to quite fit the use cases we want anyway.

**Comment by andrew-m-leonard** [comment]
From a group discussion on where and how we use the attestations, the required use case of allowing a wider scope if 3rd party builders, it makes more sense to create a new github repository and a "contribution" process. I will create a new issue to discuss
